version: "3.8"

services:
  music_service:
    image: ${REGISTRY_URL}music_service:${DEVELOP_VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/workspace
    ports:
      - ${MUSIC_SERVICE_EXTERNAL_PORT}:${MUSIC_SERVICE_INTERNAL_PORT}
  file_server:
    env_file: .env
    ports:
      - ${MINIO_DASHBOARD_PORT}:${MINIO_DASHBOARD_PORT}
      - ${MINIO_API_PORT}:${MINIO_API_PORT}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-admin}
    command: server /DATA --console-address ":${MINIO_DASHBOARD_PORT}"
  mongo:
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
