version: "3.8"

services:
  music_service:
    container_name: music_service
    image: ${REGISTRY_URL}music_service:${DEPLOY_VERSION}
    restart: unless-stopped
    depends_on:
      - file_server
    networks:
      - backend
  file_server:
    container_name: file_server
    image: minio/minio:RELEASE.2022-04-01T03-41-39Z
    restart: always
    networks:
      - backend
    volumes:
      - file_storage:/DATA
  mongo:
    container_name: mongo
    image: mongo:5
    restart: always
    networks:
      - backend
    volumes:
      - mongo:/data/db

volumes:
  file_storage:
    driver: local
  mongo:
    driver: local

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
