version: "3"

services:
  music_service:
    container_name: music_service
    image: music_service
    restart: unless-stopped
    networks:
      - backend
  file_server:
    container_name: file_server
    image: quay.io/minio/minio:RELEASE.2022-04-09T15-09-52Z
    restart: always
    networks:
      - backend
    volumes:
      - file_storage:/DATA
  mongo:
    container_name: mongo
    image: mongo:5
    restart: always
    networks:
      - backend
    volumes:
      - mongo:/data/db

volumes:
  file_storage:
    driver: local
  mongo:
    driver: local

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.123.0.0/24
