apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: music-service-server
  template:
    metadata:
      labels:
        run: music-service-server
    spec:
      containers:
        - name: music-service-api-server
          image: 52.79.185.138/jungmir/music_service
          ports:
            - containerPort: 8090
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: api-server-svc
spec:
  type: NodePort
  selector:
    run: api-server-svc
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30007
