apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deploy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: music-deploy-test
  template:
    metadata:
      labels:
        run: music-deploy-test
    spec:
      containers:
        - name: music-test-pod
          image: 52.79.185.138/jungmir/music_service
          ports:
            - containerPort: 8090
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
