apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -f docker-compose.prod.yaml -o ./k8s
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: file-server
  name: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -f docker-compose.prod.yaml -o ./k8s
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: file-server
    spec:
      containers:
        - args:
            - server
            - /DATA
            - --console-address
            - :9001
          env:
            - name: MINIO_ROOT_PASSWORD
              value: adminadmin
            - name: MINIO_ROOT_USER
              value: admin
          image: quay.io/minio/minio:RELEASE.2022-04-09T15-09-52Z
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:/minio/health/live
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: file-server
          ports:
            - containerPort: 9001
            - containerPort: 9000
          resources: {}
          volumeMounts:
            - mountPath: /DATA
              name: file-storage
      restartPolicy: Always
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: file-storage
status: {}
