apiVersion: v1
kind: Service
metadata:
  labels:
    run: music-service-server
  name: ms-canary-svc
spec:
  selector:
    run: music-service-server
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30007
      protocol: TCP
  type: NodePort
