apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service-server-stable
  labels:
    run: music-service-server
    version: stable
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      run: music-service-server
      version: stable
      color: green
  template:
    metadata:
      labels:
        run: music-service-server
        version: stable
        color: green
    spec:
      containers:
        - name: music-service-api-server
          image: 52.79.185.138/jungmir/music_service:v0.1
          ports:
            - containerPort: 8090
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          imagePullPolicy: Always
