apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service-server
  labels:
    run: music-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: music-service-server
      color: blue
  template:
    metadata:
      labels:
        run: music-service-server
        color: blue
    spec:
      containers:
        - name: music-service-api-server
          image: 52.79.185.138/jungmir/music_service
          ports:
            - containerPort: 8090
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service-server
  labels:
    run: music-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: music-service-server
      color: green
  template:
    metadata:
      labels:
        run: music-service-server
        color: green
    spec:
      containers:
        - name: music-service-api-server
          image: 52.79.185.138/jungmir/music_service
          ports:
            - containerPort: 8090
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: music-service-server
  name: ms-blue-green-svc
spec:
  selector:
    run: music-service-server
    color: blue
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30007
      protocol: TCP
  type: NodePort
