apiVersion: v1
kind: Service
metadata:
  name: ms-server
  labels:
    name: ms-server
  namespace: ms-server
spec:
  selector:
    run: music-service-server
    color: blue
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30007
      protocol: TCP
  type: NodePort
